SEO-178107-JS-Diagram-Changes
syncfusion-content/ej2-diagrams-docs pull request #28
Opened 2023-12-11 08:09 UTC by Sharly-Atieno

Hi @MallikaRK,

Worked on page with redirect for js diagram.

Regards,
Sharly A.

2023-12-11 08:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178107-JS-Diagram-Changes](https://jenkins.syncfusion.com/job/Content/job/ej2-diagrams-docs/34/console)**

2023-12-11 08:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-178107-JS-Diagram-Changes](https://jenkins.syncfusion.com/job/Content/job/ej2-diagrams-docs/34/)<br/>**

2023-12-14 07:29 UTC, Yvone-Atieno requested changes
Commented

2023-12-14 07:29 UTC, Yvone-Atieno commented on ej2-javascript/diagram/js/data-binding.md
>  To learn more about data manager, refer to [`Data Manager`](../api/diagram/dataSourceModel).
Check the above link

2023-12-14 07:43 UTC, Sharly-Atieno commented on ej2-javascript/diagram/js/data-binding.md
>  To learn more about data manager, refer to [`Data Manager`](../api/diagram/dataSourceModel).
Updated the link

2023-12-14 07:52 UTC, Yvone-Atieno approved these changes
Approved

2023-12-14 13:08 UTC, Aishwarya-Ganesan approved these changes
fine.

2023-12-15 05:22 UTC, merged